"""
Does the IO-VNBD model transfer to our SIMULATED logs? (Spoiler: no.)

This exists to justify, with numbers, why `docs/benchmarks.md` has no
`full_ml` row. The ablation harness replays `data/replay/sim_*.jsonl`, which
are generated by our own physics model. Running an IO-VNBD-trained speed model
over synthetic IMU and publishing the resulting drift would be measuring the
simulator, not the model — and it would look like a benchmark.

    python ml/check_sim_transfer.py

Re-run this after any change to the simulator's IMU synthesis. If the numbers
ever come good, the simulator has become realistic enough to carry an ML row.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import ROOT  # noqa: E402

REPO = ROOT.parent
MODEL = REPO / "apps" / "web" / "public" / "models" / "speed_model.onnx"
SCALER = REPO / "apps" / "web" / "public" / "models" / "scaler.json"


def load_log(path: Path, rate_hz: int):
    """Decimate a replay log to the model's rate, carrying GNSS speed forward.

    ★ Build the reference at FULL rate and decimate afterwards. ★ Decimating
    first phase-locks the sampler to a grid the 1 Hz GNSS fixes may never land
    on — IMU at t = 20, 40, 60... takes t ≡ 20 (mod 100) while fixes arrive at
    t ≡ 0, so every window gets a reference speed of "unknown" and the check
    silently reports a truth of 0 km/h.
    """
    ts, imus, speeds = [], [], []
    last = np.nan
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if "imu" not in r:
            continue
        g = r.get("gnss")
        if g and g.get("speedMps") is not None:
            last = g["speedMps"]
        i = r["imu"]
        ts.append(r["t"])
        speeds.append(last)
        imus.append([i["ax"], i["ay"], i["az"], i["gx"], i["gy"], i["gz"]])

    ts = np.array(ts)
    imus = np.array(imus)
    speeds = np.array(speeds, dtype=float)

    keep, nxt = [], None
    for k, t in enumerate(ts):
        if nxt is None or t >= nxt:
            keep.append(k)
            nxt = t + 1000 / rate_hz
    return imus[keep], speeds[keep]


def main() -> None:
    if not MODEL.exists():
        raise SystemExit(f"no model at {MODEL} — run ml/export.py first")
    import onnxruntime as ort

    sc = json.loads(SCALER.read_text())
    mean, std = np.array(sc["mean"]), np.array(sc["std"])
    w, rate = sc["windowSamples"], sc["sampleRateHz"]
    sess = ort.InferenceSession(str(MODEL), providers=["CPUExecutionProvider"])

    logs = sorted((REPO / "data" / "replay").glob("sim_*.jsonl"))
    if not logs:
        raise SystemExit("no sim_*.jsonl logs found")

    print(f"  {'log':<20}{'n':>5}{'truth':>9}{'predicted':>11}{'MAE':>9}{'corr':>8}")
    worst_corr = 1.0
    for path in logs:
        imu, ref = load_log(path, rate)
        X, y = [], []
        for s in range(0, len(imu) - w, w // 2):
            if np.isfinite(ref[s + w - 1]):
                X.append(imu[s : s + w])
                y.append(ref[s + w - 1])
        if not X:
            continue
        Xn = ((np.array(X) - mean) / std).transpose(0, 2, 1).astype(np.float32)
        y = np.array(y)
        p = np.clip(sess.run(None, {"imu_window": Xn})[0].reshape(-1), 0, None)
        corr = float(np.corrcoef(p, y)[0, 1]) if y.std() > 1e-6 else float("nan")
        worst_corr = min(worst_corr, corr if np.isfinite(corr) else 1.0)
        print(
            f"  {path.stem:<20}{len(y):>5}{y.mean()*3.6:>7.1f} km/h"
            f"{p.mean()*3.6:>9.1f} km/h{np.abs(p-y).mean():>7.2f} m/s{corr:>+8.3f}"
        )

    print(
        "\n  For reference, on HELD-OUT REAL sequences the same model scores\n"
        "  2.93 m/s MAE and R2 0.79 (ml/results/train_metrics.json)."
    )
    print(
        "\n  VERDICT: the model does not transfer to synthetic IMU. It answers\n"
        "  roughly the same speed whether the simulated vehicle is doing 34 or\n"
        "  81 km/h, because the simulator's vibration is one 20 Hz sine plus\n"
        "  Gaussian noise and the model keys on a road/tyre spectrum that is\n"
        "  simply not in there. So there is NO full_ml row in docs/benchmarks.md:\n"
        "  a number from this would measure the simulator, not the model."
    )


if __name__ == "__main__":
    main()
