"""
Do the IO-VNBD models transfer to our SIMULATED logs? (Spoiler: no.)

This exists to justify, with numbers, why `docs/benchmarks.md` has no ML row —
for the Phase 8 speed regressor AND for Phase 13's motion classifier. The ablation harness replays `data/replay/sim_*.jsonl`, which
are generated by our own physics model. Running an IO-VNBD-trained speed model
over synthetic IMU and publishing the resulting drift would be measuring the
simulator, not the model — and it would look like a benchmark.

    python ml/check_sim_transfer.py

Re-run this after any change to the simulator's IMU synthesis. If the numbers
ever come good, the simulator has become realistic enough to carry an ML row.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import ROOT  # noqa: E402

REPO = ROOT.parent
# ★ ml/export/, NOT apps/web/public/models/ ★
# Only the folded-weights JSON is copied into the app — nav-core evaluates the
# network itself and no ONNX runtime ships. Pointing this check at the app's
# directory made it fail with "run ml/export.py first" on a repository where
# export.py had already run, which is a confusing way to say "wrong path".
MODEL = ROOT / "export" / "speed_model.onnx"
MOTION_MODEL = ROOT / "export" / "motion_model.onnx"
SCALER = REPO / "apps" / "web" / "public" / "models" / "scaler.json"
MOTION_WEIGHTS = ROOT / "export" / "motion_model.json"


def load_log(path: Path, rate_hz: int):
    """Decimate a replay log to the model's rate, carrying GNSS speed forward.

    ★ Build the reference at FULL rate and decimate afterwards. ★ Decimating
    first phase-locks the sampler to a grid the 1 Hz GNSS fixes may never land
    on — IMU at t = 20, 40, 60... takes t ≡ 20 (mod 100) while fixes arrive at
    t ≡ 0, so every window gets a reference speed of "unknown" and the check
    silently reports a truth of 0 km/h.
    """
    ts, imus, speeds = [], [], []
    last = np.nan
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if "imu" not in r:
            continue
        g = r.get("gnss")
        if g and g.get("speedMps") is not None:
            last = g["speedMps"]
        i = r["imu"]
        ts.append(r["t"])
        speeds.append(last)
        imus.append([i["ax"], i["ay"], i["az"], i["gx"], i["gy"], i["gz"]])

    ts = np.array(ts)
    imus = np.array(imus)
    speeds = np.array(speeds, dtype=float)

    keep, nxt = [], None
    for k, t in enumerate(ts):
        if nxt is None or t >= nxt:
            keep.append(k)
            nxt = t + 1000 / rate_hz
    return imus[keep], speeds[keep]


GRAVITY = 9.80665


def motion_channels(imu: np.ndarray, speed: np.ndarray, heading: np.ndarray, dt_s: float):
    """The six channels Phase 13 Model 2 reads, built from a simulated log.

    Identical construction to ml/data/preprocess_motion.py and to
    `motionChannels` in NavigationEngine.ts: up from the mean specific force,
    forward from the horizontal direction that best explains the longitudinal
    acceleration, and the gyro's vertical component with the other two entering
    only as a magnitude.
    """
    accel, gyro = imu[:, 0:3], imu[:, 3:6]
    up = accel.mean(axis=0)
    up = up / max(1e-9, np.linalg.norm(up))
    vertical = accel @ up
    linear = accel - np.outer(vertical, up)

    dv = np.zeros(len(speed))
    step = 5
    if len(speed) > step:
        dv[step:] = (speed[step:] - speed[:-step]) / (step * dt_s)
    drive = np.where(np.isfinite(dv), dv, 0.0)

    fwd = (linear * drive[:, None]).sum(axis=0)
    fwd = fwd - (fwd @ up) * up
    norm = np.linalg.norm(fwd)
    if norm < 1e-9:
        seed = np.array([1.0, 0.0, 0.0])
        fwd = seed - (seed @ up) * up
        norm = max(1e-9, np.linalg.norm(fwd))
    fwd = fwd / norm
    right = np.cross(up, fwd)

    w_up = gyro @ up
    w_horiz = np.sqrt(np.maximum(0.0, (gyro**2).sum(axis=1) - w_up**2))
    channels = np.column_stack(
        [
            linear @ fwd,
            linear @ right,
            vertical - GRAVITY,
            w_up,
            w_horiz,
            np.linalg.norm(accel, axis=1) - GRAVITY,
        ]
    )

    # Reference labels from the simulator's own GNSS, using the same rules the
    # training labeller applies to the CAN bus.
    yaw = np.zeros(len(heading))
    if len(heading) > 1:
        d = np.diff(np.unwrap(np.deg2rad(heading)))
        yaw[1:] = d / dt_s
    labels = np.full(len(speed), 2, dtype=int)  # STRAIGHT
    stopped = speed < 0.5
    labels[stopped] = 1  # IDLING — a simulated engine is always running
    moving = ~stopped
    labels[moving & (dv > 0.7)] = 5   # ACCELERATING
    labels[moving & (dv < -0.7)] = 6  # BRAKING
    labels[moving & (yaw > 0.15)] = 3   # TURNING_LEFT
    labels[moving & (yaw < -0.15)] = 4  # TURNING_RIGHT
    return channels, labels


def load_log_full(path: Path):
    """Every IMU sample with the GNSS speed and heading carried forward."""
    ts, imus, speeds, headings = [], [], [], []
    last_speed, last_heading = np.nan, np.nan
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if "imu" not in r:
            continue
        g = r.get("gnss")
        if g:
            if g.get("speedMps") is not None:
                last_speed = g["speedMps"]
            if g.get("headingDeg") is not None:
                last_heading = g["headingDeg"]
        i = r["imu"]
        ts.append(r["t"])
        speeds.append(last_speed)
        headings.append(last_heading)
        imus.append([i["ax"], i["ay"], i["az"], i["gx"], i["gy"], i["gz"]])
    return (
        np.array(ts),
        np.array(imus),
        np.array(speeds, dtype=float),
        np.array(headings, dtype=float),
    )


def check_motion() -> str:
    """The same question for Phase 13's classifier, which nobody had asked."""
    if not MOTION_MODEL.exists() or not MOTION_WEIGHTS.exists():
        return "  (no motion model exported — run ml/export_motion.py)"
    import onnxruntime as ort

    weights = json.loads(MOTION_WEIGHTS.read_text())
    classes = weights["classes"]
    mean = np.array(weights["scaler"]["mean"])
    std = np.array(weights["scaler"]["std"])
    w = weights["windowSamples"]
    sess = ort.InferenceSession(str(MOTION_MODEL), providers=["CPUExecutionProvider"])

    print(f"\n  {'log':<20}{'n':>6}{'accuracy':>10}{'predicted most often':>24}")
    accuracies = []
    for path in sorted((REPO / "data" / "replay").glob("sim_*.jsonl")):
        ts, imu, speed, heading = load_log_full(path)
        if len(imu) < 200:
            continue
        # Decimate to the model's 10 Hz.
        keep, nxt = [], None
        for k, t in enumerate(ts):
            if nxt is None or t >= nxt:
                keep.append(k)
                nxt = t + 100
        imu, speed, heading = imu[keep], speed[keep], heading[keep]
        ok = np.isfinite(speed) & np.isfinite(heading)
        imu, speed, heading = imu[ok], speed[ok], heading[ok]
        if len(imu) < 100:
            continue

        channels, labels = motion_channels(imu, speed, heading, 0.1)
        X, y = [], []
        for start in range(0, len(channels) - w, w // 2):
            X.append(channels[start : start + w])
            y.append(labels[start + w - 1])
        if not X:
            continue

        Xn = ((np.array(X) - mean) / std).transpose(0, 2, 1).astype(np.float32)
        logits = sess.run(None, {"imu_window": Xn})[0]
        pred = logits.argmax(axis=1)
        y = np.array(y)
        acc = float((pred == y).mean())
        accuracies.append(acc)
        counts = np.bincount(pred, minlength=len(classes))
        dominant = classes[int(counts.argmax())]
        share = counts.max() / counts.sum()
        print(
            f"  {path.stem:<20}{len(y):>6}{acc:>9.1%}"
            f"{dominant + f' ({share:.0%})':>24}"
        )

    if not accuracies:
        return "  (no usable simulated logs)"
    return (
        f"\n  Mean accuracy on simulated logs: {np.mean(accuracies):.1%}.\n"
        "  On the held-out REAL journey the same model scores 57.4 % accuracy\n"
        "  and 0.480 macro-F1 (ml/results/motion_metrics.json).\n"
    )


def main() -> None:
    if not MODEL.exists():
        raise SystemExit(f"no model at {MODEL} — run ml/export.py first")
    import onnxruntime as ort

    sc = json.loads(SCALER.read_text())
    mean, std = np.array(sc["mean"]), np.array(sc["std"])
    w, rate = sc["windowSamples"], sc["sampleRateHz"]
    sess = ort.InferenceSession(str(MODEL), providers=["CPUExecutionProvider"])

    logs = sorted((REPO / "data" / "replay").glob("sim_*.jsonl"))
    if not logs:
        raise SystemExit("no sim_*.jsonl logs found")

    print("\n  MODEL 1 — the IO-VNBD speed regressor on simulated IMU\n")
    print(f"  {'log':<20}{'n':>5}{'truth':>9}{'predicted':>11}{'MAE':>9}{'corr':>8}")
    for path in logs:
        imu, ref = load_log(path, rate)
        X, y = [], []
        for s in range(0, len(imu) - w, w // 2):
            if np.isfinite(ref[s + w - 1]):
                X.append(imu[s : s + w])
                y.append(ref[s + w - 1])
        if not X:
            continue
        Xn = ((np.array(X) - mean) / std).transpose(0, 2, 1).astype(np.float32)
        y = np.array(y)
        p = np.clip(sess.run(None, {"imu_window": Xn})[0].reshape(-1), 0, None)
        corr = float(np.corrcoef(p, y)[0, 1]) if y.std() > 1e-6 else float("nan")
        print(
            f"  {path.stem:<20}{len(y):>5}{y.mean()*3.6:>7.1f} km/h"
            f"{p.mean()*3.6:>9.1f} km/h{np.abs(p-y).mean():>7.2f} m/s{corr:>+8.3f}"
        )

    print(
        "\n  For reference, on HELD-OUT REAL sequences the same model scores\n"
        "  2.93 m/s MAE and R2 0.79 (ml/results/train_metrics.json)."
    )

    print("\n  MODEL 2 — the motion-state classifier on simulated IMU")
    motion_summary = check_motion()
    print(motion_summary)

    print(
        "  VERDICT: neither model transfers to synthetic IMU. The speed model\n"
        "  answers roughly the same speed whether the simulated vehicle is doing\n"
        "  34 or 81 km/h, because the simulator's vibration is one 20 Hz sine\n"
        "  plus Gaussian noise and the model keys on a road and tyre spectrum\n"
        "  that is simply not in there. The classifier sees the same synthetic\n"
        "  signal and has the same problem.\n\n"
        "  So there is NO ML row in docs/benchmarks.md. A number from this would\n"
        "  measure the simulator, not the model — which is exactly the kind of\n"
        "  row that looks like a benchmark and is not one.\n\n"
        "  ★ THIS IS A STATEMENT ABOUT THE LOGS, NOT ABOUT THE MODELS. ★\n"
        "  Both are measured properly on held-out REAL data, in\n"
        "  ml/results/train_metrics.json and ml/results/motion_metrics.json.\n"
        "  Re-run this after any change to the simulator's IMU synthesis: if the\n"
        "  numbers ever come good, the simulator has become realistic enough to\n"
        "  carry an ML row and the ablation should gain one."
    )


if __name__ == "__main__":
    main()
