'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { NavMode, SensorSample } from '@pathpulse/nav-core';
import {
  CITY_VEHICLE,
  HIGHWAY_VEHICLE,
  ForegroundSource,
  NativeSource,
  RecordingWrapper,
  ReplaySource,
  SimulationSource,
  WebSource,
  type RouteGeoJson,
  type SensorSource,
} from '@pathpulse/sensor-sources';
import cityRoute from '../../../data/routes/route_city.json';
import highwayRoute from '../../../data/routes/route_highway.json';
import type { GnssFix } from './useGeolocation';

/**
 * `replay` is the demo-day backup.
 *
 * The simulator is deterministic, which makes it a fine demo and a poor
 * backup: a backup has to survive the thing it is backing up. `demo.jsonl` is
 * a flat file of recorded numbers with the outage already deleted from it, so
 * none of the vehicle model, the route parser or the simulation pipeline has
 * to work for it to play. Built by scripts/make-demo-log.mjs.
 */
export type SourceKind = 'simulation' | 'live' | 'replay';
export type RouteKey = 'city' | 'highway';

// JSON imports widen `type: "Feature"` to `string`, so the literal types no
// longer match. The files are generated by scripts/make-routes.mjs and their
// shape is asserted by the sensor-sources tests, so the cast is safe.
function label(route: RouteGeoJson, kind: string): string {
  // Read from the generated metadata so the dropdown can never drift from the
  // actual route on disk.
  const p = route.properties ?? {};
  const km = p.lengthM ? (p.lengthM / 1000).toFixed(2) : '?';
  const turns = p.turns ?? '?';
  const stops = p.stopsAtFraction?.length ?? 0;
  return `${kind} — ${km} km, ${turns} turns${stops ? `, ${stops} stops` : ''}`;
}

export const ROUTES: Record<RouteKey, { route: RouteGeoJson; label: string }> = {
  city: {
    route: cityRoute as unknown as RouteGeoJson,
    label: label(cityRoute as unknown as RouteGeoJson, 'City'),
  },
  highway: {
    route: highwayRoute as unknown as RouteGeoJson,
    label: label(highwayRoute as unknown as RouteGeoJson, 'Highway'),
  },
};

export interface SensorSourceState {
  fix: GnssFix | null;
  mode: NavMode;
  sample: SensorSample | null;
  imuHz: number;
  gnssHz: number;
  isRunning: boolean;
  inOutage: boolean;
  progress: number;
  /**
   * Whether the running source can actually produce fixes.
   *
   * ★ THE SILENT FAILURE THIS EXISTS TO END ★
   * `NativeSource.start()` catches a denied location permission, sets
   * `capabilities.hasGnss = false` and returns — never starting a watch. That
   * flag was read by nothing. `PermissionGate` watches `useGeolocation`, a
   * different code path entirely, so it never learned about the denial either.
   * The result on a real phone: IMU at 53 Hz, GNSS at 0.00 Hz, "waiting for
   * first fix…" for ever, and no explanation anywhere. The app looked alive
   * and simply never found you.
   */
  gnssAvailable: boolean;
  /**
   * Whether the live source is delivering rotation rate. Undefined until the
   * first motion event settles it. See SensorSourceCapabilities.hasGyro — a
   * missing gyroscope reads as a yaw rate of zero, which is a valid number
   * meaning the opposite thing, and dead reckoning then cannot turn at all.
   */
  hasGyro?: boolean;
  sourceName: string;
  recordedCount: number;
}

/**
 * Owns the active SensorSource and turns its samples into something the map
 * can draw.
 *
 * Phase 1's raw geolocation hook is still used for the live-permission UI;
 * this sits alongside it and will be the single input to NavigationEngine in
 * Phase 4.
 */
/** Progress from a source that exposes it (the replay log), else 0. */
function replayProgress(source: SensorSource | null): number {
  if (!source) return 0;
  const p = (source as { progressFraction?: unknown }).progressFraction;
  return typeof p === 'number' && Number.isFinite(p) ? p : 0;
}

export function useSensorSource(
  kind: SourceKind,
  routeKey: RouteKey,
  /** Called for every raw sample, before any UI throttling. */
  onSample?: (s: SensorSample) => void,
) {
  const [state, setState] = useState<SensorSourceState>({
    fix: null,
    mode: 'INITIALIZING',
    sample: null,
    imuHz: 0,
    gnssHz: 0,
    isRunning: false,
    inOutage: false,
    progress: 0,
    gnssAvailable: true,
    sourceName: '',
    recordedCount: 0,
  });

  const simRef = useRef<SimulationSource | null>(null);
  const recRef = useRef<RecordingWrapper | null>(null);
  // Live mode resolves to NativeSource inside the APK and WebSource in a
  // browser. Same interface either way, so nothing downstream changes.
  const webRef = useRef<SensorSource | null>(null);
  /**
   * A play() that arrived before the source existed.
   *
   * The live and replay sources are built behind a promise, so there is a
   * window after selecting them where there is nothing to start. See play().
   */
  const pendingPlayRef = useRef(false);
  /** Mirrors state.isRunning for the source-rebuild effect, which cannot read state. */
  const isRunningRef = useRef(false);
  /**
   * Bumped to force the source to be built again from scratch.
   *
   * ★ WHY A REBUILD AND NOT A RESTART ★
   * `NativeSource.start()` decides `hasGnss` once — from the permission and
   * location-services state at that instant — and then early-returns on every
   * later call because it is already running. `reset()` only ever handled the
   * simulator. So a phone that started with Location switched off was stuck:
   * turning Location on changed nothing, Restart did nothing, and the only
   * escape was killing the app. Measured exactly that on a real device.
   *
   * Tearing the source down and constructing a new one is the only thing that
   * makes it ask again.
   */
  const [rebuildToken, setRebuildToken] = useState(0);
  const lastFixRef = useRef<GnssFix | null>(null);

  // Rate measurement: counted, never hardcoded.
  const imuTimes = useRef<number[]>([]);
  const gnssTimes = useRef<number[]>([]);

  const onSampleRef = useRef(onSample);
  onSampleRef.current = onSample;

  const handleSample = useCallback((s: SensorSample) => {
    // Feed the navigation engine first, at full sensor rate.
    onSampleRef.current?.(s);
    const now = s.t;
    if (s.imu) {
      imuTimes.current.push(now);
      if (imuTimes.current.length > 100) imuTimes.current.shift();
    }
    if (s.gnss) {
      gnssTimes.current.push(now);
      if (gnssTimes.current.length > 20) gnssTimes.current.shift();
      lastFixRef.current = {
        lat: s.gnss.lat,
        lon: s.gnss.lon,
        accuracyM: s.gnss.accuracyM,
        speedMps: s.gnss.speedMps ?? null,
        headingDeg: s.gnss.headingDeg ?? null,
        altitudeM: null,
        timestamp: s.t,
      };
    }

    /**
     * Arrival rate over a window that ENDS NOW, not at the last arrival.
     *
     * ★ A RATE COMPUTED BETWEEN ARRIVALS CANNOT FALL TO ZERO ★
     * Measured on a real walk: the HUD read `gnss 1.00 Hz` while the banner
     * beside it read `no fix for 76s`. Both came from the same samples and
     * only one was true. Spanning first-to-last arrival means a receiver that
     * stops is described by the last twenty fixes it managed, for ever — the
     * window is full, none of it ages out, and the number freezes at whatever
     * the rate was when the signal died. That is the single most misleading
     * thing this HUD can do, because the whole point of the panel is that its
     * numbers can be trusted against each other.
     *
     * Ending the span at the current sample instead makes silence part of the
     * measurement, so the reading decays toward zero for exactly as long as
     * nothing arrives. It is also still correct for a slow receiver: 20 fixes
     * at 0.2 Hz spans 100 s either way.
     */
    const rate = (arr: number[], nowMs: number) => {
      if (arr.length < 2) return 0;
      const span = (Math.max(nowMs, arr[arr.length - 1]!) - arr[0]!) / 1000;
      return span > 0 ? (arr.length - 1) / span : 0;
    };

    const sim = simRef.current;
    const inOutage = sim ? sim.isInOutage() : false;

    setState((prev) => ({
      ...prev,
      sample: s,
      fix: lastFixRef.current,
      // Without the Phase 4 engine there is no propagation yet, so during an
      // outage the marker holds its last fix. Labelled DEAD_RECKONING because
      // that is the mode we are in; the estimate itself arrives in Phase 4.
      mode: inOutage ? 'DEAD_RECKONING' : s.gnss ? deriveGnssMode(s.gnss.accuracyM) : prev.mode,
      imuHz: rate(imuTimes.current, now),
      gnssHz: rate(gnssTimes.current, now),
      // Read on the tick rather than at start: the platform only reveals
      // whether it has a gyroscope once the first motion event arrives.
      hasGyro: webRef.current?.capabilities.hasGyro,
      inOutage,
      // Whichever source is driving. Reading only the simulator left the
      // progress bar at zero for an entire replay, so a stalled backup and a
      // running one looked identical.
      progress: sim
        ? sim.progressFraction
        : replayProgress(webRef.current),
      isRunning: sim ? sim.isRunning : prev.isRunning,
      recordedCount: recRef.current?.sampleCount ?? 0,
    }));
  }, []);

  // Rebuild the source whenever the selection changes.
  /** Start a source and report back what it turned out to be able to do. */
  const startSource = useCallback(async (src: SensorSource) => {
    try {
      await src.start();
    } finally {
      // Read AFTER start: the permission request happens inside it, and a
      // denial is only knowable once it has resolved.
      //
      // `isRunning` is set here too, not only in play(). A source rebuilt by a
      // switch resets it to false, so a pending start would leave the UI
      // saying "Start" while samples were already arriving.
      isRunningRef.current = true;
      setState((p) => ({
        ...p,
        isRunning: true,
        gnssAvailable: src.capabilities.hasGnss !== false,
      }));
    }
  }, []);

  useEffect(() => {
    // ★ CARRY THE INTENT ACROSS A SOURCE SWITCH ★
    // The earlier fix only covered "no source exists yet". Switching BETWEEN
    // sources is worse: the outgoing source is still in the ref, so a
    // synchronous play() starts the one being torn down and the incoming one
    // never starts — while isRunning is set true regardless. Measured on the
    // device: picking "This phone" showed RUNNING with imu 0.0 Hz and gnss
    // 0.00 Hz, and a manual Pause then Start took the IMU straight to 60 Hz.
    // If it was running before the switch, it should be running after.
    if (isRunningRef.current) pendingPlayRef.current = true;
    simRef.current?.stop();
    webRef.current?.stop();
    simRef.current = null;
    webRef.current = null;
    recRef.current = null;
    lastFixRef.current = null;
    imuTimes.current = [];
    gnssTimes.current = [];

    if (kind === 'simulation') {
      const sim = new SimulationSource({
        route: ROUTES[routeKey].route,
        vehicle: routeKey === 'highway' ? HIGHWAY_VEHICLE : CITY_VEHICLE,
        seed: 1337,
      });
      const rec = new RecordingWrapper(sim);
      rec.onSample(handleSample);
      simRef.current = sim;
      recRef.current = rec;
      setState((p) => ({
        ...p,
        fix: null,
        mode: 'INITIALIZING',
        sourceName: sim.capabilities.name,
        isRunning: false,
        progress: 0,
        gnssAvailable: true,
      }));
    } else if (kind === 'replay') {
      let cancelled = false;
      setState((p) => ({
        ...p,
        fix: null,
        mode: 'INITIALIZING',
        sourceName: 'Replay — loading…',
        isRunning: false,
        progress: 0,
      }));
      fetch('replay/demo.jsonl')
        .then((r) => (r.ok ? r.text() : Promise.reject(new Error('missing'))))
        .then((text) => {
          if (cancelled) return;
          const src = ReplaySource.fromJsonl(text, 'Demo replay');
          src.onSample(handleSample);
          webRef.current = src;
          setState((p) => ({ ...p, sourceName: src.capabilities.name }));
          if (pendingPlayRef.current) {
            pendingPlayRef.current = false;
            void startSource(src);
          }
        })
        .catch(() => {
          if (cancelled) return;
          // Say so rather than sitting on "loading" for ever: the backup
          // failing is exactly when someone needs to know quickly.
          setState((p) => ({ ...p, sourceName: 'Replay — demo.jsonl missing' }));
        });
      return () => {
        cancelled = true;
        webRef.current?.stop();
      };
    } else {
      let cancelled = false;
      /**
       * ★ CLEAR THE OUTGOING SOURCE'S STATE FIRST ★
       * The simulation and replay branches both reset `fix`, `mode` and
       * `progress` synchronously. This one did not, and it is the only branch
       * that resolves its source asynchronously — so for the whole of that
       * await the panel still showed the simulation's last fix and mode, under
       * the heading "This phone".
       *
       * `gnssAvailable` is deliberately NOT cleared here. It means "this source
       * can produce fixes", startSource() sets it from the real capabilities the
       * moment the source exists, and page.tsx renders a "Location is off"
       * banner when it is false. Clearing it during the await would flash that
       * alarm on every switch to Live, before anything had gone wrong.
       */
      setState((p) => ({
        ...p,
        fix: null,
        mode: 'INITIALIZING',
        sourceName: 'This phone — starting…',
        isRunning: false,
        progress: 0,
      }));
      /**
       * ★ PHASE 15 — THREE SOURCES, MOST CAPABLE FIRST ★
       *
       * ForegroundSource is the native SensorManager loop inside a foreground
       * service: full rate, and it keeps running with the screen off, which is
       * what a real drive through a tunnel actually looks like.
       *
       * NativeSource is the same APK without that plugin — an older build, or
       * a device where the service could not start. It reads the WebView's own
       * DeviceMotion, which Android throttles to about 1 Hz in the background.
       *
       * WebSource is the browser.
       *
       * Each is CHECKED rather than assumed. An APK updated from a build
       * without the plugin would otherwise start a source that receives
       * nothing, and the app would look broken with nothing to point at.
       */
      void (async () => {
        const foreground = await ForegroundSource.isAvailable();
        if (cancelled) return { foreground, native: false };
        return { foreground, native: foreground ? false : await NativeSource.isAvailable() };
      })().then(({ foreground, native }) => {
        if (cancelled) return;
        const src: SensorSource = foreground
          ? new ForegroundSource()
          : native
            ? new NativeSource()
            : new WebSource();
        src.onSample(handleSample);
        webRef.current = src;
        setState((p) => ({ ...p, sourceName: src.capabilities.name }));
        if (pendingPlayRef.current) {
          pendingPlayRef.current = false;
          void startSource(src).catch(() => {
            /**
             * ★ AVAILABLE IS NOT THE SAME AS STARTABLE ★
             *
             * isAvailable() answers "is the plugin in this build?", and the
             * ladder above trusted that to mean the source would run. It does
             * not. Android can refuse to start the foreground service at the
             * moment it is asked — MIUI and HyperOS refuse routinely, and for
             * apps that are visibly in the foreground — and no check made
             * beforehand can predict it.
             *
             * So the ladder now has a rung after the attempt as well. Losing
             * the native loop costs the screen-off sample rate and nothing
             * else: WebSource reads the same sensors through the WebView, and
             * Live works. Refusing to fall back cost the entire feature.
             */
            if (cancelled) return;
            const fallback = new WebSource();
            fallback.onSample(handleSample);
            webRef.current = fallback;
            setState((p) => ({
              ...p,
              // Named for what it is. The native loop was asked for and
              // refused, and a panel that hides that is how a demo-day
              // question about screen-off behaviour gets the wrong answer.
              sourceName: `${fallback.capabilities.name} (native loop refused)`,
            }));
            void startSource(fallback);
          });
        }
      });
      return () => {
        cancelled = true;
        simRef.current?.stop();
        webRef.current?.stop();
      };
    }

    return () => {
      simRef.current?.stop();
      webRef.current?.stop();
    };
  }, [kind, routeKey, rebuildToken, handleSample, startSource]);

  /**
   * ★ START MEANT NOTHING IF THE SOURCE WAS NOT READY YET ★
   * The live source is built behind `NativeSource.isAvailable()`, which is a
   * promise — so `webRef` is empty for a moment after Live is selected. Tap
   * Start inside that moment and `play()` had nothing to start, yet still set
   * `isRunning: true`: the button flipped to Stop, no fix ever arrived, and
   * the app looked exactly like it could not find you. That is the same race
   * that made the Demo button open onto a dead map, in the one place a user
   * hits it every single time.
   *
   * Now an unfulfilled play is remembered and honoured the moment the source
   * exists.
   */
  const play = useCallback(() => {
    const src = simRef.current ?? webRef.current;
    if (src) void startSource(src);
    else pendingPlayRef.current = true;
    isRunningRef.current = true;
    setState((p) => ({ ...p, isRunning: true }));
  }, [startSource]);

  const pause = useCallback(() => {
    pendingPlayRef.current = false;
    isRunningRef.current = false;
    simRef.current?.stop();
    webRef.current?.stop();
    setState((p) => ({ ...p, isRunning: false }));
  }, []);

  const reset = useCallback(() => {
    const sim = simRef.current;
    if (!sim) {
      // ★ LIVE AND REPLAY REBUILD RATHER THAN RESTART ★
      // `NativeSource.start()` decides `hasGnss` once and early-returns
      // afterwards because it is already running, and this function used to
      // handle only the simulator — so a phone that started with Location
      // switched off was stuck for good. Turning Location on changed nothing,
      // Restart did nothing, and killing the app was the only way out.
      // Measured exactly that on a device. Constructing a fresh source is the
      // only thing that makes it ask again, and it rewinds the replay log too.
      pendingPlayRef.current = isRunningRef.current;
      lastFixRef.current = null;
      imuTimes.current = [];
      gnssTimes.current = [];
      setState((p) => ({
        ...p,
        fix: null,
        mode: 'INITIALIZING',
        isRunning: false,
        inOutage: false,
        progress: 0,
        gnssAvailable: true,
      }));
      setRebuildToken((t) => t + 1);
      return;
    }
    sim.stop();
    const fresh = new SimulationSource({
      route: ROUTES[routeKey].route,
      vehicle: routeKey === 'highway' ? HIGHWAY_VEHICLE : CITY_VEHICLE,
      seed: 1337,
    });
    const rec = new RecordingWrapper(fresh);
    rec.onSample(handleSample);
    simRef.current = fresh;
    recRef.current = rec;
    lastFixRef.current = null;
    imuTimes.current = [];
    gnssTimes.current = [];
    setState((p) => ({
      ...p,
      fix: null,
      mode: 'INITIALIZING',
      isRunning: false,
      inOutage: false,
      progress: 0,
      recordedCount: 0,
    }));
  }, [routeKey, handleSample]);

  const setSpeed = useCallback((rate: number) => {
    simRef.current?.setPlaybackRate(rate);
  }, []);

  const triggerOutage = useCallback((durationMs = 60_000) => {
    simRef.current?.startOutageNow(durationMs);
  }, []);

  const downloadRecording = useCallback(() => {
    const rec = recRef.current;
    if (!rec || rec.sampleCount === 0) return;
    const blob = new Blob([rec.toJsonl()], { type: 'application/x-ndjson' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pathpulse_${routeKey}_${rec.sampleCount}.jsonl`;
    a.click();
    URL.revokeObjectURL(url);
  }, [routeKey]);

  return useMemo(
    () => ({ ...state, play, pause, reset, setSpeed, triggerOutage, downloadRecording }),
    [state, play, pause, reset, setSpeed, triggerOutage, downloadRecording],
  );
}

function deriveGnssMode(accuracyM: number): NavMode {
  return accuracyM > 25 ? 'GNSS_DEGRADED' : 'GNSS';
}
