'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { NavMode, SensorSample } from '@pathpulse/nav-core';
import {
  CITY_VEHICLE,
  HIGHWAY_VEHICLE,
  NativeSource,
  RecordingWrapper,
  SimulationSource,
  WebSource,
  type RouteGeoJson,
  type SensorSource,
} from '@pathpulse/sensor-sources';
import cityRoute from '../../../data/routes/route_city.json';
import highwayRoute from '../../../data/routes/route_highway.json';
import type { GnssFix } from './useGeolocation';

export type SourceKind = 'simulation' | 'live';
export type RouteKey = 'city' | 'highway';

// JSON imports widen `type: "Feature"` to `string`, so the literal types no
// longer match. The files are generated by scripts/make-routes.mjs and their
// shape is asserted by the sensor-sources tests, so the cast is safe.
function label(route: RouteGeoJson, kind: string): string {
  // Read from the generated metadata so the dropdown can never drift from the
  // actual route on disk.
  const p = route.properties ?? {};
  const km = p.lengthM ? (p.lengthM / 1000).toFixed(2) : '?';
  const turns = p.turns ?? '?';
  const stops = p.stopsAtFraction?.length ?? 0;
  return `${kind} — ${km} km, ${turns} turns${stops ? `, ${stops} stops` : ''}`;
}

export const ROUTES: Record<RouteKey, { route: RouteGeoJson; label: string }> = {
  city: {
    route: cityRoute as unknown as RouteGeoJson,
    label: label(cityRoute as unknown as RouteGeoJson, 'City'),
  },
  highway: {
    route: highwayRoute as unknown as RouteGeoJson,
    label: label(highwayRoute as unknown as RouteGeoJson, 'Highway'),
  },
};

export interface SensorSourceState {
  fix: GnssFix | null;
  mode: NavMode;
  sample: SensorSample | null;
  imuHz: number;
  gnssHz: number;
  isRunning: boolean;
  inOutage: boolean;
  progress: number;
  sourceName: string;
  recordedCount: number;
}

/**
 * Owns the active SensorSource and turns its samples into something the map
 * can draw.
 *
 * Phase 1's raw geolocation hook is still used for the live-permission UI;
 * this sits alongside it and will be the single input to NavigationEngine in
 * Phase 4.
 */
export function useSensorSource(
  kind: SourceKind,
  routeKey: RouteKey,
  /** Called for every raw sample, before any UI throttling. */
  onSample?: (s: SensorSample) => void,
) {
  const [state, setState] = useState<SensorSourceState>({
    fix: null,
    mode: 'INITIALIZING',
    sample: null,
    imuHz: 0,
    gnssHz: 0,
    isRunning: false,
    inOutage: false,
    progress: 0,
    sourceName: '',
    recordedCount: 0,
  });

  const simRef = useRef<SimulationSource | null>(null);
  const recRef = useRef<RecordingWrapper | null>(null);
  // Live mode resolves to NativeSource inside the APK and WebSource in a
  // browser. Same interface either way, so nothing downstream changes.
  const webRef = useRef<SensorSource | null>(null);
  const lastFixRef = useRef<GnssFix | null>(null);

  // Rate measurement: counted, never hardcoded.
  const imuTimes = useRef<number[]>([]);
  const gnssTimes = useRef<number[]>([]);

  const onSampleRef = useRef(onSample);
  onSampleRef.current = onSample;

  const handleSample = useCallback((s: SensorSample) => {
    // Feed the navigation engine first, at full sensor rate.
    onSampleRef.current?.(s);
    const now = s.t;
    if (s.imu) {
      imuTimes.current.push(now);
      if (imuTimes.current.length > 100) imuTimes.current.shift();
    }
    if (s.gnss) {
      gnssTimes.current.push(now);
      if (gnssTimes.current.length > 20) gnssTimes.current.shift();
      lastFixRef.current = {
        lat: s.gnss.lat,
        lon: s.gnss.lon,
        accuracyM: s.gnss.accuracyM,
        speedMps: s.gnss.speedMps ?? null,
        headingDeg: s.gnss.headingDeg ?? null,
        altitudeM: null,
        timestamp: s.t,
      };
    }

    const rate = (arr: number[]) => {
      if (arr.length < 2) return 0;
      const span = (arr[arr.length - 1]! - arr[0]!) / 1000;
      return span > 0 ? (arr.length - 1) / span : 0;
    };

    const sim = simRef.current;
    const inOutage = sim ? sim.isInOutage() : false;

    setState((prev) => ({
      ...prev,
      sample: s,
      fix: lastFixRef.current,
      // Without the Phase 4 engine there is no propagation yet, so during an
      // outage the marker holds its last fix. Labelled DEAD_RECKONING because
      // that is the mode we are in; the estimate itself arrives in Phase 4.
      mode: inOutage ? 'DEAD_RECKONING' : s.gnss ? deriveGnssMode(s.gnss.accuracyM) : prev.mode,
      imuHz: rate(imuTimes.current),
      gnssHz: rate(gnssTimes.current),
      inOutage,
      progress: sim ? sim.progressFraction : 0,
      isRunning: sim ? sim.isRunning : prev.isRunning,
      recordedCount: recRef.current?.sampleCount ?? 0,
    }));
  }, []);

  // Rebuild the source whenever the selection changes.
  useEffect(() => {
    simRef.current?.stop();
    webRef.current?.stop();
    simRef.current = null;
    webRef.current = null;
    recRef.current = null;
    lastFixRef.current = null;
    imuTimes.current = [];
    gnssTimes.current = [];

    if (kind === 'simulation') {
      const sim = new SimulationSource({
        route: ROUTES[routeKey].route,
        vehicle: routeKey === 'highway' ? HIGHWAY_VEHICLE : CITY_VEHICLE,
        seed: 1337,
      });
      const rec = new RecordingWrapper(sim);
      rec.onSample(handleSample);
      simRef.current = sim;
      recRef.current = rec;
      setState((p) => ({
        ...p,
        fix: null,
        mode: 'INITIALIZING',
        sourceName: sim.capabilities.name,
        isRunning: false,
        progress: 0,
      }));
    } else {
      let cancelled = false;
      void NativeSource.isAvailable().then((native) => {
        if (cancelled) return;
        const src: SensorSource = native ? new NativeSource() : new WebSource();
        src.onSample(handleSample);
        webRef.current = src;
        setState((p) => ({ ...p, sourceName: src.capabilities.name }));
      });
      return () => {
        cancelled = true;
        simRef.current?.stop();
        webRef.current?.stop();
      };
    }

    return () => {
      simRef.current?.stop();
      webRef.current?.stop();
    };
  }, [kind, routeKey, handleSample]);

  const play = useCallback(() => {
    if (simRef.current) void simRef.current.start();
    else void webRef.current?.start();
    setState((p) => ({ ...p, isRunning: true }));
  }, []);

  const pause = useCallback(() => {
    simRef.current?.stop();
    webRef.current?.stop();
    setState((p) => ({ ...p, isRunning: false }));
  }, []);

  const reset = useCallback(() => {
    const sim = simRef.current;
    if (!sim) return;
    sim.stop();
    const fresh = new SimulationSource({
      route: ROUTES[routeKey].route,
      vehicle: routeKey === 'highway' ? HIGHWAY_VEHICLE : CITY_VEHICLE,
      seed: 1337,
    });
    const rec = new RecordingWrapper(fresh);
    rec.onSample(handleSample);
    simRef.current = fresh;
    recRef.current = rec;
    lastFixRef.current = null;
    imuTimes.current = [];
    gnssTimes.current = [];
    setState((p) => ({
      ...p,
      fix: null,
      mode: 'INITIALIZING',
      isRunning: false,
      inOutage: false,
      progress: 0,
      recordedCount: 0,
    }));
  }, [routeKey, handleSample]);

  const setSpeed = useCallback((rate: number) => {
    simRef.current?.setPlaybackRate(rate);
  }, []);

  const triggerOutage = useCallback((durationMs = 60_000) => {
    simRef.current?.startOutageNow(durationMs);
  }, []);

  const downloadRecording = useCallback(() => {
    const rec = recRef.current;
    if (!rec || rec.sampleCount === 0) return;
    const blob = new Blob([rec.toJsonl()], { type: 'application/x-ndjson' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pathpulse_${routeKey}_${rec.sampleCount}.jsonl`;
    a.click();
    URL.revokeObjectURL(url);
  }, [routeKey]);

  return useMemo(
    () => ({ ...state, play, pause, reset, setSpeed, triggerOutage, downloadRecording }),
    [state, play, pause, reset, setSpeed, triggerOutage, downloadRecording],
  );
}

function deriveGnssMode(accuracyM: number): NavMode {
  return accuracyM > 25 ? 'GNSS_DEGRADED' : 'GNSS';
}
